export enum RoleEnum {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_LEASING_CLIENT = 'ROLE_LEASING_CLIENT',
  ROLE_LEASING_COMPANY = 'ROLE_LEASING_COMPANY',
  ROLE_LEASING_COMPANY_HEAD_OF_SALES = 'ROLE_LEASING_COMPANY_HEAD_OF_SALES',
  ROLE_LEASING_COMPANY_HEAD_OF_ANALITICS = 'ROLE_LEASING_COMPANY_HEAD_OF_ANALITICS',
  ROLE_LEASING_COMPANY_ANALITIC = 'ROLE_LEASING_COMPANY_ANALITIC',
  ROLE_LEASING_COMPANY_REGION_MANAGER = 'ROLE_LEASING_COMPANY_REGION_MANAGER',
  ROLE_LEASING_COMPANY_MANAGER = 'ROLE_LEASING_COMPANY_MANAGER',
  ROLE_LEASING_COMPANY_SALES = 'ROLE_LEASING_COMPANY_SALES'
}
